name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync to S3 with proper MIME types
        run: |
          # First, sync all files normally
          aws s3 sync dist/ s3://knowelist.com/ --delete
          
          # Then fix MIME types for specific file types
          echo "Setting MIME types for JavaScript files..."
          find dist -name "*.js" -type f | while read file; do
            s3_path="${file#dist/}"
            echo "Processing JS: $s3_path"
            aws s3 cp "s3://knowelist.com/$s3_path" "s3://knowelist.com/$s3_path" \
              --metadata-directive REPLACE \
              --content-type "application/javascript" \
              --cache-control "public, max-age=31536000, immutable"
          done
          
          echo "Setting MIME types for MJS files..."
          find dist -name "*.mjs" -type f | while read file; do
            s3_path="${file#dist/}"
            echo "Processing MJS: $s3_path"
            aws s3 cp "s3://knowelist.com/$s3_path" "s3://knowelist.com/$s3_path" \
              --metadata-directive REPLACE \
              --content-type "application/javascript" \
              --cache-control "public, max-age=31536000, immutable"
          done
          
          echo "Setting MIME types for CSS files..."
          find dist -name "*.css" -type f | while read file; do
            s3_path="${file#dist/}"
            echo "Processing CSS: $s3_path"
            aws s3 cp "s3://knowelist.com/$s3_path" "s3://knowelist.com/$s3_path" \
              --metadata-directive REPLACE \
              --content-type "text/css" \
              --cache-control "public, max-age=31536000, immutable"
          done
          
          echo "Setting MIME types for HTML files..."
          find dist -name "*.html" -type f | while read file; do
            s3_path="${file#dist/}"
            echo "Processing HTML: $s3_path"
            aws s3 cp "s3://knowelist.com/$s3_path" "s3://knowelist.com/$s3_path" \
              --metadata-directive REPLACE \
              --content-type "text/html" \
              --cache-control "no-cache, no-store, must-revalidate"
          done

      - name: Configure S3 for SPA routing
        run: |
          # Set up proper S3 website configuration for SPA
          aws s3 website s3://knowelist.com --index-document index.html --error-document 404.html
          
          echo "S3 website configuration completed successfully"

      - name: Invalidate CloudFront (if applicable)
        run: |
          # Add CloudFront invalidation if you have a distribution
          # aws cloudfront create-invalidation --distribution-id YOUR_DISTRIBUTION_ID --paths "/*"
          echo "CloudFront invalidation skipped - add distribution ID if needed"
